<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {

        DB::table('school_students')->insert([
            ['student_code' => '000001', 'gender' => 'Male', 'full_name' => 'Nguyễn Văn An'],
            ['student_code' => '000002', 'gender' => 'Female', 'full_name' => 'Trần Thị Bích Ngọc'],
            ['student_code' => '000003', 'gender' => 'Male', 'full_name' => 'Phạm Minh Đức'],
            ['student_code' => '000004', 'gender' => 'Male', 'full_name' => 'Lê Hoàng Nam'],
            ['student_code' => '000005', 'gender' => 'Female', 'full_name' => 'Đỗ Thị Lan'],
            ['student_code' => '000006', 'gender' => 'Male', 'full_name' => 'Ngô Văn Huy'],
            ['student_code' => '000007', 'gender' => 'Female', 'full_name' => 'Vũ Thị Mai'],
            ['student_code' => '000008', 'gender' => 'Male', 'full_name' => 'Bùi Quốc Khánh'],
            ['student_code' => '000009', 'gender' => 'Female', 'full_name' => 'Trịnh Thùy Dung'],
            ['student_code' => '000010', 'gender' => 'Male', 'full_name' => 'Phan Anh Tuấn'],
            ['student_code' => '000011', 'gender' => 'Female', 'full_name' => 'Nguyễn Thị Hạnh'],
            ['student_code' => '000012', 'gender' => 'Male', 'full_name' => 'Lý Văn Long'],
            ['student_code' => '000013', 'gender' => 'Female', 'full_name' => 'Hoàng Thu Trang'],
            ['student_code' => '000014', 'gender' => 'Male', 'full_name' => 'Đặng Quang Huy'],
            ['student_code' => '000015', 'gender' => 'Female', 'full_name' => 'Trần Mỹ Linh'],
            ['student_code' => '000016', 'gender' => 'Male', 'full_name' => 'Nguyễn Thành Công'],
            ['student_code' => '000017', 'gender' => 'Male', 'full_name' => 'Lưu Hải Đăng'],
            ['student_code' => '000018', 'gender' => 'Female', 'full_name' => 'Phạm Thu Hương'],
            ['student_code' => '000019', 'gender' => 'Male', 'full_name' => 'Đinh Văn Kiên'],
            ['student_code' => '000020', 'gender' => 'Female', 'full_name' => 'Lê Thị Thảo'],
            ['student_code' => '000021', 'gender' => 'Male', 'full_name' => 'Trương Hữu Phước'],
            ['student_code' => '000022', 'gender' => 'Female', 'full_name' => 'Nguyễn Thị Yến'],
            ['student_code' => '000023', 'gender' => 'Male', 'full_name' => 'Phan Quốc Bảo'],
            ['student_code' => '000024', 'gender' => 'Female', 'full_name' => 'Đoàn Thị Như Quỳnh'],
            ['student_code' => '000025', 'gender' => 'Male', 'full_name' => 'Nguyễn Duy Khánh'],
            ['student_code' => '000026', 'gender' => 'Female', 'full_name' => 'Trần Ngọc Ánh'],
            ['student_code' => '000027', 'gender' => 'Male', 'full_name' => 'Lưu Văn Toàn'],
            ['student_code' => '000028', 'gender' => 'Female', 'full_name' => 'Phạm Bảo Trâm'],
            ['student_code' => '000029', 'gender' => 'Male', 'full_name' => 'Võ Minh Tâm'],
            ['student_code' => '000030', 'gender' => 'Female', 'full_name' => 'Ngô Thị Kim Chi'],

            ['student_code' => '000031', 'gender' => 'Male', 'full_name' => 'Trần Quang Hưng'],
            ['student_code' => '000032', 'gender' => 'Female', 'full_name' => 'Nguyễn Thị Thu Trang'],
            ['student_code' => '000033', 'gender' => 'Male', 'full_name' => 'Lê Quốc Khánh'],
            ['student_code' => '000034', 'gender' => 'Female', 'full_name' => 'Phạm Thị Hồng Nhung'],
            ['student_code' => '000035', 'gender' => 'Male', 'full_name' => 'Đỗ Anh Dũng'],
            ['student_code' => '000036', 'gender' => 'Female', 'full_name' => 'Vũ Thị Thanh Hoa'],
            ['student_code' => '000037', 'gender' => 'Male', 'full_name' => 'Nguyễn Trọng Phú'],
            ['student_code' => '000038', 'gender' => 'Female', 'full_name' => 'Bùi Thị Ngọc Lan'],
            ['student_code' => '000039', 'gender' => 'Male', 'full_name' => 'Phan Hoàng Duy'],
            ['student_code' => '000040', 'gender' => 'Female', 'full_name' => 'Trịnh Minh Thư'],
            ['student_code' => '000041', 'gender' => 'Male', 'full_name' => 'Ngô Văn Cường'],
            ['student_code' => '000042', 'gender' => 'Female', 'full_name' => 'Lý Thị Mai Hương'],
            ['student_code' => '000043', 'gender' => 'Male', 'full_name' => 'Hoàng Văn Tài'],
            ['student_code' => '000044', 'gender' => 'Female', 'full_name' => 'Đặng Thị Thu Hà'],
            ['student_code' => '000045', 'gender' => 'Male', 'full_name' => 'Phạm Đức Mạnh'],
            ['student_code' => '000046', 'gender' => 'Female', 'full_name' => 'Nguyễn Thị Quỳnh Anh'],
            ['student_code' => '000047', 'gender' => 'Male', 'full_name' => 'Lê Hữu Nghĩa'],
            ['student_code' => '000048', 'gender' => 'Female', 'full_name' => 'Trần Thị Thanh Tâm'],
            ['student_code' => '000049', 'gender' => 'Male', 'full_name' => 'Vũ Minh Hiếu'],
            ['student_code' => '000050', 'gender' => 'Female', 'full_name' => 'Nguyễn Bảo Trân'],
            ['student_code' => '000051', 'gender' => 'Male', 'full_name' => 'Đỗ Văn Lâm'],
            ['student_code' => '000052', 'gender' => 'Female', 'full_name' => 'Phan Thị Ngọc Diệp'],
            ['student_code' => '000053', 'gender' => 'Male', 'full_name' => 'Lưu Đức Anh'],
            ['student_code' => '000054', 'gender' => 'Female', 'full_name' => 'Ngô Thị Hương Giang'],
            ['student_code' => '000055', 'gender' => 'Male', 'full_name' => 'Trần Quốc Hòa'],
            ['student_code' => '000056', 'gender' => 'Female', 'full_name' => 'Phạm Thu Trang'],
            ['student_code' => '000057', 'gender' => 'Male', 'full_name' => 'Đinh Tiến Dũng'],

            ['student_code' => '000058', 'gender' => 'Female', 'full_name' => 'Nguyễn Thị Thanh'],
            ['student_code' => '000059', 'gender' => 'Female', 'full_name' => 'Bùi Hồng Phúc'],
            ['student_code' => '000060', 'gender' => 'Female', 'full_name' => 'Lý Thị Kim Oanh'],

        ]);



        // ===== USERS =====
        DB::table('users')->insert([
            // --- Admin + Staff ---
            [
                'name' => 'Admin User',
                'email' => 'admin@gmail.com',
                'password' => Hash::make('123456'),
                'role' => 'Admin',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Staff 1',
                'email' => 'staff1@gmail.com',
                'password' => Hash::make('123456'),
                'role' => 'Staff',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Staff 2',
                'email' => 'staff2@gmail.com',
                'password' => Hash::make('123456'),
                'role' => 'Staff',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],





            ['name' => 'Nguyễn Văn An', 'email' => 'student1@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Thị Bích Ngọc', 'email' => 'student2@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Minh Đức', 'email' => 'student3@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lê Hoàng Nam', 'email' => 'student4@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đỗ Thị Lan', 'email' => 'student5@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ngô Văn Huy', 'email' => 'student6@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vũ Thị Mai', 'email' => 'student7@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bùi Quốc Khánh', 'email' => 'student8@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trịnh Thùy Dung', 'email' => 'student9@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phan Anh Tuấn', 'email' => 'student10@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thị Hạnh', 'email' => 'student11@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lý Văn Long', 'email' => 'student12@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],

            // --- Bổ sung từ 13 đến 60 ---
            ['name' => 'Hoàng Thu Trang', 'email' => 'student13@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đặng Quang Huy', 'email' => 'student14@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Mỹ Linh', 'email' => 'student15@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thành Công', 'email' => 'student16@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lưu Hải Đăng', 'email' => 'student17@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Thu Hương', 'email' => 'student18@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đinh Văn Kiên', 'email' => 'student19@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lê Thị Thảo', 'email' => 'student20@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trương Hữu Phước', 'email' => 'student21@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thị Yến', 'email' => 'student22@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phan Quốc Bảo', 'email' => 'student23@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đoàn Thị Như Quỳnh', 'email' => 'student24@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Duy Khánh', 'email' => 'student25@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Ngọc Ánh', 'email' => 'student26@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lưu Văn Toàn', 'email' => 'student27@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Bảo Trâm', 'email' => 'student28@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Võ Minh Tâm', 'email' => 'student29@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ngô Thị Kim Chi', 'email' => 'student30@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Quang Hưng', 'email' => 'student31@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thị Thu Trang', 'email' => 'student32@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lê Quốc Khánh', 'email' => 'student33@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Thị Hồng Nhung', 'email' => 'student34@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đỗ Anh Dũng', 'email' => 'student35@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vũ Thị Thanh Hoa', 'email' => 'student36@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Trọng Phú', 'email' => 'student37@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bùi Thị Ngọc Lan', 'email' => 'student38@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phan Hoàng Duy', 'email' => 'student39@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trịnh Minh Thư', 'email' => 'student40@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ngô Văn Cường', 'email' => 'student41@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lý Thị Mai Hương', 'email' => 'student42@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hoàng Văn Tài', 'email' => 'student43@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đặng Thị Thu Hà', 'email' => 'student44@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Đức Mạnh', 'email' => 'student45@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thị Quỳnh Anh', 'email' => 'student46@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lê Hữu Nghĩa', 'email' => 'student47@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Thị Thanh Tâm', 'email' => 'student48@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vũ Minh Hiếu', 'email' => 'student49@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Bảo Trân', 'email' => 'student50@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đỗ Văn Lâm', 'email' => 'student51@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phan Thị Ngọc Diệp', 'email' => 'student52@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lưu Đức Anh', 'email' => 'student53@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ngô Thị Hương Giang', 'email' => 'student54@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Quốc Hòa', 'email' => 'student55@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Thu Trang', 'email' => 'student56@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đinh Tiến Dũng', 'email' => 'student57@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thị Thanh', 'email' => 'student58@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bùi Hồng Phúc', 'email' => 'student59@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lý Thị Kim Oanh', 'email' => 'student60@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Student', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],



            ['name' => 'Nguyễn Thị Mai ', 'email' => 'parent1@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Văn Quang' , 'email' => 'parent2@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Thị Hồng'  , 'email' => 'parent3@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lê Văn Nam'     , ' email' => 'parent4@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đỗ Thị Thu'     , 'email' => 'parent5@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ngô Văn Tùng', 'email' => 'parent6@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vũ Thị Lan', 'email' => 'parent7@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bùi Văn Dũng', 'email' => 'parent8@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trịnh Thị Ngọc', 'email' => 'parent9@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phan Văn Toàn', 'email' => 'parent10@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thị Hoa', 'email' => 'parent11@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lý Văn Hưng', 'email' => 'parent12@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hoàng Thị Hạnh', 'email' => 'parent13@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đặng Văn Đức', 'email' => 'parent14@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Thị Tâm', 'email' => 'parent15@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Văn Cường', 'email' => 'parent16@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lưu Thị Yến', 'email' => 'parent17@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Văn Đạt', 'email' => 'parent18@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đinh Thị Thảo', 'email' => 'parent19@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lê Văn Bình', 'email' => 'parent20@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trương Thị Hòa', 'email' => 'parent21@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Văn Hào', 'email' => 'parent22@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phan Thị Dung', 'email' => 'parent23@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đoàn Văn Hiếu', 'email' => 'parent24@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thị Ngọc', 'email' => 'parent25@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Văn Lâm', 'email' => 'parent26@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lưu Thị Kim', 'email' => 'parent27@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Văn Minh', 'email' => 'parent28@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Võ Thị Hường', 'email' => 'parent29@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ngô Văn Hải', 'email' => 'parent30@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Thị Vân', 'email' => 'parent31@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Văn Phúc', 'email' => 'parent32@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lê Thị Thu', 'email' => 'parent33@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Văn Hùng', 'email' => 'parent34@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đỗ Thị Hậu', 'email' => 'parent35@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vũ Văn Kiên', 'email' => 'parent36@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Thị Nhung', 'email' => 'parent37@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bùi Văn Thịnh', 'email' => 'parent38@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phan Thị Nga', 'email' => 'parent39@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trịnh Văn Hậu', 'email' => 'parent40@gmail.com', 'password' => Hash::make('1Two'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ngô Thị Hằng', 'email' => 'parent41@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lý Văn Long', 'email' => 'parent42@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hoàng Thị Liên', 'email' => 'parent43@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đặng Văn Tài', 'email' => 'parent44@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Thị Hòa', 'email' => 'parent45@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Văn Tuấn', 'email' => 'parent46@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lê Thị Hồng', 'email' => 'parent47@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Văn Hòa', 'email' => 'parent48@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Vũ Thị Phương', 'email' => 'parent49@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Văn Đạt', 'email' => 'parent50@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đỗ Thị Hương', 'email' => 'parent51@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phan Văn Duy', 'email' => 'parent52@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lưu Thị Hòa', 'email' => 'parent53@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Ngô Văn Khánh', 'email' => 'parent54@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Trần Thị Hà', 'email' => 'parent55@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Phạm Văn Phong', 'email' => 'parent56@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Đinh Thị Hồng', 'email' => 'parent57@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Nguyễn Văn Hưng', 'email' => 'parent58@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Bùi Thị Mai', 'email' => 'parent59@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Lý Văn Khánh', 'email' => 'parent60@gmail.com', 'password' => Hash::make('123456'), 'role' => 'Parent', 'status' => 'Active', 'created_at' => now(), 'updated_at' => now()],


        ]);





        DB::table('rooms')->insert([
            [
                'room_code' => 'A101',
                'area' => 'Khu A',
                'capacity' => 8,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A102',
                'area' => 'Khu A',
                'capacity' => 8,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A103',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A104',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A105',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A201',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Full',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'room_code' => 'A202',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Maintenance',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A203',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A204',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A205',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A301',
                'area' => 'Khu A',
                'capacity' => 5,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'room_code' => 'A302',
                'area' => 'Khu A',
                'capacity' => 8,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A303',
                'area' => 'Khu A',
                'capacity' => 8,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Female Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A304',
                'area' => 'Khu A',
                'capacity' => 8,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Female Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A305',
                'capacity' => 8,
                'area' => 'Khu A',
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Female Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A401',
                'area' => 'Khu A',
                'capacity' => 8,
                'status' => 'Full',
                'price'     => 200000,
                'description' => 'Female Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'room_code' => 'A402',
                'area' => 'Khu A',
                'capacity' => 8,
                'status' => 'Maintenance',
                'price'     => 200000,
                'description' => 'Female Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'A403',
                'area' => 'Khu A',
                'capacity' => 8,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Female Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'B101',
                'area' => 'Khu B',
                'capacity' => 8,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Female Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'B102',
                'area' => 'Khu B',
                'capacity' => 8,
                'area' => 'Khu B',
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Female Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'B103',
                'area' => 'Khu B',
                'capacity' => 4,
                'status' => 'Full',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'room_code' => 'B104',
                'area' => 'Khu B',
                'capacity' => 8,
                'capacity' => 4,
                'status' => 'Maintenance',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'B105',
                'area' => 'Khu B',
                'capacity' => 6,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'B201',
                'area' => 'Khu B',
                'capacity' => 6,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'room_code' => 'B202',
                'area' => 'Khu B',
                'capacity' => 4,
                'status' => 'Available',
                'price'     => 200000,
                'description' => 'Male Dormitory',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        // ===== STUDENTS =====

        DB::table('students')->insert([
            [
                'user_id' => 4,
                'room_id' => 1,
                'student_code' => '000001',
                'full_name' => 'Nguyễn Văn An',
                'phone' => '0901111111',
                'gender' => 'Male',
                'date_of_birth' => '2006-05-15',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'room_id' => 13,
                'student_code' => '000002',
                'full_name' => 'Trần Thị Bích Ngọc',
                'phone' => '0901111112',
                'gender' => 'Female',
                'date_of_birth' => '2006-07-20',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'room_id' => 1,
                'student_code' => '000003',
                'full_name' => 'Phạm Minh Đức',
                'phone' => '0901111113',
                'gender' => 'Male',
                'date_of_birth' => '2006-03-11',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'room_id' => 1,
                'student_code' => '000004',
                'full_name' => 'Lê Hoàng Nam',
                'phone' => '0901111114',
                'gender' => 'Male',
                'date_of_birth' => '2006-06-22',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'room_id' => 13,
                'student_code' => '000005',
                'full_name' => 'Đỗ Thị Lan',
                'phone' => '0901222114',
                'gender' => 'Female',
                'date_of_birth' => '2006-06-15',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'room_id' => 1,
                'student_code' => '000006',
                'full_name' => 'Ngô Văn Huy',
                'phone' => '0901333114',
                'gender' => 'Male',
                'date_of_birth' => '2006-07-10',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 10,
                'room_id' => 13,
                'student_code' => '000007',
                'full_name' => 'Vũ Thị Mai',
                'phone' => '0901444114',
                'gender' => 'Female',
                'date_of_birth' => '2006-09-01',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 11,
                'room_id' => 1,
                'student_code' => '000008',
                'full_name' => 'Bùi Quốc Khánh',
                'phone' => '0901555114',
                'gender' => 'Male',
                'date_of_birth' => '2006-10-05',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 12,
                'room_id' => 13,
                'student_code' => '000009',
                'full_name' => 'Trịnh Thùy Dung',
                'phone' => '0901666114',
                'gender' => 'Female',
                'date_of_birth' => '2006-11-20',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 13,
                'room_id' => 1,
                'student_code' => '000010',
                'full_name' => 'Phan Anh Tuấn',
                'phone' => '0901777114',
                'gender' => 'Male',
                'date_of_birth' => '2006-11-21',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 14,
                'room_id' => 13,
                'student_code' => '000011',
                'full_name' => 'Nguyễn Thị Hạnh',
                'phone' => '0901646114',
                'gender' => 'Male',
                'date_of_birth' => '2006-11-27',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 15,
                'room_id' => 1,
                'student_code' => '000012',
                'full_name' => 'Lý Văn Long',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-11-27',
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 16,
                'room_id' => 13,
                'student_code' => '000013',
                'full_name' => 'Hoàng Thu Trang',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 17,
                'room_id' => 1,
                'student_code' => '000014',
                'full_name' => 'Đặng Quang Huy',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 18,
                'room_id' => 13,
                'student_code' => '000015',
                'full_name' => 'Trần Mỹ Linh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 19,
                'room_id' => 2,
                'student_code' => '000016',
                'full_name' => 'Nguyễn Thành Công',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //

            [
                'user_id' => 20,
                'room_id' => 2,
                'student_code' => '000017',
                'full_name' => 'Lưu Hải Đăng',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 21,
                'room_id' => 13,
                'student_code' => '000018',
                'full_name' => 'Phạm Thu Hương',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 22,
                'room_id' => 2,
                'student_code' => '000019',
                'full_name' => 'Đinh Văn Kiên',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 23,
                'room_id' => 14,
                'student_code' => '000020',
                'full_name' => 'Lê Thị Thảo',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 24,
                'room_id' => 3,
                'student_code' => '000021',
                'full_name' => 'Trương Hữu Phước',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 25,
                'room_id' => 14,
                'student_code' => '000022',
                'full_name' => 'Nguyễn Thị Yến',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 26,
                'room_id' => 4,
                'student_code' => '000023',
                'full_name' => 'Phan Quốc Bảo',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 27,
                'room_id' => 14,
                'student_code' => '000024',
                'full_name' => 'Đoàn Thị Như Quỳnh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 28,
                'room_id' => 5,
                'student_code' => '000025',
                'full_name' => 'Nguyễn Duy Khánh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 29,
                'room_id' => 15,
                'student_code' => '000026',
                'full_name' => 'Trần Ngọc Ánh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 30,
                'room_id' => 7,
                'student_code' => '000027',
                'full_name' => 'Lưu Văn Toàn',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 31,
                'room_id' => 15,
                'student_code' => '000028',
                'full_name' => 'Phạm Bảo Trâm',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 32,
                'room_id' => 6,
                'student_code' => '000029',
                'full_name' => 'Võ Minh Tâm',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 33,
                'room_id' => 17,
                'student_code' => '000030',
                'full_name' => 'Ngô Thị Kim Chi',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2006-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 34,
                'room_id' => 6,
                'student_code' => '000031',
                'full_name' => 'Trần Quang Hưng',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 35,
                'room_id' => 18,
                'student_code' => '000032',
                'full_name' => 'Nguyễn Thị Thu Trang',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'user_id' => 36,
                'room_id' => 18,
                'student_code' => '000033',
                'full_name' => 'Lê Quốc Khánh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 37,
                'room_id' => 18,
                'student_code' => '000034',
                'full_name' => 'Phạm Thị Hồng Nhung',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 38,
                'room_id' => 18,
                'student_code' => '000035',
                'full_name' => 'Đỗ Anh Dũng',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 39,
                'room_id' => 18,
                'student_code' => '000036',
                'full_name' => 'Vũ Thị Thanh Hoa',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 40,
                'room_id' => 18,
                'student_code' => '000037',
                'full_name' => 'Nguyễn Trọng Phú',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 41,
                'room_id' => 18,
                'student_code' => '000038',
                'full_name' => 'Bùi Thị Ngọc Lan',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 42,
                'room_id' => 18,
                'student_code' => '000039',
                'full_name' => 'Phan Hoàng Duy',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 43,
                'room_id' => 18,
                'student_code' => '000040',
                'full_name' => 'Trịnh Minh Thư',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 44,
                'room_id' => 18,
                'student_code' => '000041',
                'full_name' => 'Ngô Văn Cường',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 45,
                'room_id' => 18,
                'student_code' => '000042',
                'full_name' => 'Lý Thị Mai Hương',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 46,
                'room_id' => 18,
                'student_code' => '000043',
                'full_name' => 'Hoàng Văn Tài',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 47,
                'room_id' => 18,
                'student_code' => '000044',
                'full_name' => 'Đặng Thị Thu Hà',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 48,
                'room_id' => 18,
                'student_code' => '000045',
                'full_name' => 'Phạm Đức Mạnh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 49,
                'room_id' => 18,
                'student_code' => '000046',
                'full_name' => 'Nguyễn Thị Quỳnh Anh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 50,
                'room_id' => 18,
                'student_code' => '000047',
                'full_name' => 'Lê Hữu Nghĩa',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 51,
                'room_id' => 18,
                'student_code' => '000048',
                'full_name' => 'Trần Thị Thanh Tâm',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 52,
                'room_id' => 18,
                'student_code' => '000049',
                'full_name' => 'Vũ Minh Hiếu',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 53,
                'room_id' => 18,
                'student_code' => '000050',
                'full_name' => 'Nguyễn Bảo Trân',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 54,
                'room_id' => 18,
                'student_code' => '000051',
                'full_name' => 'Đỗ Văn Lâm',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 55,
                'room_id' => 18,
                'student_code' => '000052',
                'full_name' => 'Phan Thị Ngọc Diệp',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 56,
                'room_id' => 18,
                'student_code' => '000053',
                'full_name' => 'Lưu Đức Anh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 57,
                'room_id' => 18,
                'student_code' => '000054',
                'full_name' => 'Ngô Thị Hương Giang',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 58,
                'room_id' => 18,
                'student_code' => '000055',
                'full_name' => 'Trần Quốc Hòa',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 59,
                'room_id' => 18,
                'student_code' => '000056',
                'full_name' => 'Phạm Thu Trang',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 60,
                'room_id' => 18,
                'student_code' => '000057',
                'full_name' => 'Đinh Tiến Dũng',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Male',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 61,
                'room_id' => 18,
                'student_code' => '000058',
                'full_name' => 'Nguyễn Thị Thanh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 62,
                'room_id' => 18,
                'student_code' => '000059',
                'full_name' => 'Bùi Hồng Phúc',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 63,
                'room_id' => 18,
                'student_code' => '000060',
                'full_name' => 'Lý Thị Kim Oanh',
                'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT),
                'gender' => 'Female',
                'date_of_birth' => '2007-' . str_pad(rand(01, 12), 2, '0', STR_PAD_LEFT) . '-' . str_pad(rand(01, 28), 2, '0', STR_PAD_LEFT),
                'status' => 'Active',
                'created_at' => now(),
                'updated_at' => now(),
            ],


        ]);

        // ===== PARENT_STUDENTS =====

        DB::table('parent_students')->insert([
            ['user_id' => 64, 'student_id' => 1, 'full_name' => 'Nguyễn Văn Bình', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 65, 'student_id' => 2, 'full_name' => 'Trần Thị Hoa', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 66, 'student_id' => 3, 'full_name' => 'Phạm Văn Dũng', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 67, 'student_id' => 4, 'full_name' => 'Lê Thị Hạnh', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 68, 'student_id' => 5, 'full_name' => 'Hoàng Văn Thành', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 69, 'student_id' => 6, 'full_name' => 'Đặng Thị Mai', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 70, 'student_id' => 7, 'full_name' => 'Bùi Văn Cường', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 71, 'student_id' => 8, 'full_name' => 'Phan Thị Lệ', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 72, 'student_id' => 9, 'full_name' => 'Ngô Văn Tuấn', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 73, 'student_id' => 10, 'full_name' => 'Đỗ Thị Nga', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 74, 'student_id' => 11, 'full_name' => 'Trịnh Văn Hải', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 75, 'student_id' => 12, 'full_name' => 'Vũ Thị Yến', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 76, 'student_id' => 13, 'full_name' => 'Nguyễn Văn Long', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 77, 'student_id' => 14, 'full_name' => 'Trần Thị Huệ', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 78, 'student_id' => 15, 'full_name' => 'Phạm Văn Hùng', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 79, 'student_id' => 16, 'full_name' => 'Lê Thị Thu', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 80, 'student_id' => 17, 'full_name' => 'Hoàng Văn Mạnh', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 81, 'student_id' => 18, 'full_name' => 'Đặng Thị Lan', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 82, 'student_id' => 19, 'full_name' => 'Bùi Văn Toàn', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 83, 'student_id' => 20, 'full_name' => 'Phan Thị Hòa', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 84, 'student_id' => 21, 'full_name' => 'Ngô Văn Khánh', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 85, 'student_id' => 22, 'full_name' => 'Đỗ Thị Hiền', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 86, 'student_id' => 23, 'full_name' => 'Trịnh Văn Đạt', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 87, 'student_id' => 24, 'full_name' => 'Vũ Thị Thanh', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 88, 'student_id' => 25, 'full_name' => 'Nguyễn Văn Nam', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 89, 'student_id' => 26, 'full_name' => 'Trần Thị Nhung', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 90, 'student_id' => 27, 'full_name' => 'Phạm Văn Quân', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 91, 'student_id' => 28, 'full_name' => 'Lê Thị Hằng', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 92, 'student_id' => 29, 'full_name' => 'Hoàng Văn Tâm', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 93, 'student_id' => 30, 'full_name' => 'Đặng Thị Minh', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 94, 'student_id' => 31, 'full_name' => 'Bùi Văn Giang', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 95, 'student_id' => 32, 'full_name' => 'Phan Thị Tâm', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 96, 'student_id' => 33, 'full_name' => 'Ngô Văn Kiên', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 97, 'student_id' => 34, 'full_name' => 'Đỗ Thị Oanh', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 100, 'student_id' => 35, 'full_name' => 'Trịnh Văn Đức', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 101, 'student_id' => 36, 'full_name' => 'Vũ Thị Hương', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 102, 'student_id' => 37, 'full_name' => 'Nguyễn Văn Lâm', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 103, 'student_id' => 38, 'full_name' => 'Trần Thị Vân', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 103, 'student_id' => 39, 'full_name' => 'Phạm Văn Toản', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 104, 'student_id' => 40, 'full_name' => 'Lê Thị Hà', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 105, 'student_id' => 41, 'full_name' => 'Hoàng Văn Duy', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 106, 'student_id' => 42, 'full_name' => 'Đặng Thị Hồng', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 107, 'student_id' => 43, 'full_name' => 'Bùi Văn Trường', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 108, 'student_id' => 44, 'full_name' => 'Phan Thị Liên', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 109, 'student_id' => 45, 'full_name' => 'Ngô Văn Sơn', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 110, 'student_id' => 46, 'full_name' => 'Đỗ Thị Quỳnh', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 111, 'student_id' => 47, 'full_name' => 'Trịnh Văn Hòa', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 112, 'student_id' => 48, 'full_name' => 'Vũ Thị Trang', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 113, 'student_id' => 49, 'full_name' => 'Nguyễn Văn Cường', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 114, 'student_id' => 50, 'full_name' => 'Trần Thị Dung', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 115, 'student_id' => 51, 'full_name' => 'Phạm Văn Phong', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 116, 'student_id' => 52, 'full_name' => 'Lê Thị Kim', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 117, 'student_id' => 53, 'full_name' => 'Hoàng Văn Lợi', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 118, 'student_id' => 54, 'full_name' => 'Đặng Thị Mai Anh', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 119, 'student_id' => 55, 'full_name' => 'Bùi Văn Hào', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hà Nội', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 120, 'student_id' => 56, 'full_name' => 'Phan Thị Loan', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Hải Phòng', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 121, 'student_id' => 57, 'full_name' => 'Ngô Văn Huy', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Nam Định', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 122, 'student_id' => 58, 'full_name' => 'Đỗ Thị Mai Linh', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Bắc Ninh', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 123, 'student_id' => 59, 'full_name' => 'Trịnh Văn Bảo', 'gender' => 'Male', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Thái Bình', 'created_at' => now(), 'updated_at' => now(),],
            ['user_id' => 124, 'student_id' => 60, 'full_name' => 'Vũ Thị Thảo', 'gender' => 'Female', 'phone' => '037' . str_pad(rand(0, 9999999), 7, '0', STR_PAD_LEFT), 'address' => 'Ninh Bình', 'created_at' => now(), 'updated_at' => now(),],
        ]);

        // ===== CONTRACTS =====
        $students = DB::table('students')->get();
        $contracts = [];

        foreach ($students as $student) {
            $contracts[] = [
                'student_id' => $student->id,
                'start_date' => '2025-01-01',
                'end_date' => '2025-12-31',
                'status' => 'Approved',
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }
        DB::table('contracts')->insert($contracts);

        // ===== PAYMENTS =====

        // $students = DB::table('students')->get();
        // $rooms = DB::table('rooms')->get();
        // $payments = [];

        // foreach ($students as $student) {
        //     $payments[] =
        //         [
        //             'payment_id' => 1,
        //             'student_id' => $student->id, // Nguyễn Văn An
        //             'room_id' => 1,
        //             'payment_code' => 'PMT0001',
        //             'electricity_usage' => 50.5,
        //             'water_usage' => 12.3,
        //             'total_amount' => 320000,
        //             'payment_status' => 'paid',
        //             'description' => 'Thanh toán tiền phòng tháng 1/2025',
        //             'month' => '01',
        //             'year' => '2025',
        //             'payment_date' => '2025-01-31',
        //             'created_at' => now(),
        //             'updated_at' => now(),

        //         ];
        // }

        DB::table('payments')->insert([
            [
                'payment_id' => 1,
                'student_id' => 1, // Nguyễn Văn An
                'room_id' => 1,
                'payment_code' => 'PMT0001',
                'electricity_usage' => 50.5,
                'water_usage' => 12.3,
                'total_amount' => 320000,
                'payment_status' => 'paid',
                'description' => 'Thanh toán tiền phòng tháng 1/2025',
                'month' => '01',
                'year' => '2025',
                'payment_date' => '2025-01-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'payment_id' => 2,
                'student_id' => 2, // Trần Thị Bích Ngọc
                'room_id' => 2,
                'payment_code' => 'PMT0002',
                'electricity_usage' => 40.2,
                'water_usage' => 10.8,
                'total_amount' => 310000,
                'payment_status' => 'paid',
                'description' => 'Thanh toán tiền phòng tháng 1/2025',
                'month' => '01',
                'year' => '2025',
                'payment_date' => '2025-01-31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'payment_id' => 3,
                'student_id' => 3, // Phạm Minh Đức
                'room_id' => 1,
                'payment_code' => 'PMT0003',
                'electricity_usage' => 45.7,
                'water_usage' => 11.5,
                'total_amount' => 315000,
                'payment_status' => 'unpaid',
                'description' => 'Thanh toán tiền phòng tháng 2/2025',
                'month' => '02',
                'year' => '2025',
                'payment_date' => '2025-02-28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // [
            //     'payment_id' => 4,
            //     'student_id' => 4, // Đỗ Thị Lan
            //     'room_id' => null, // chưa ở phòng
            //     'payment_code' => 'PMT0004',
            //     'electricity_usage' => 0,
            //     'water_usage' => 0,
            //     'total_amount' => 0,
            //     'payment_status' => 'unpaid',
            //     'description' => 'Chưa phát sinh thanh toán',
            //     'payment_date' => null,
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            // [
            //     'payment_id' => 5,
            //     'student_id' => 1, // Nguyễn Văn An
            //     'room_id' => 1,
            //     'payment_code' => 'PMT0005',
            //     'electricity_usage' => 52.4,
            //     'water_usage' => 13.0,
            //     'total_amount' => 1220000,
            //     'payment_status' => 'paid',
            //     'description' => 'Thanh toán tiền phòng tháng 2/2025',
            //     'payment_date' => '2025-02-28',
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
        ]);



        // DB::table('school_students')->insert([
        //     ['student_code' => '000001', 'full_name' => 'Nguyễn Văn An'],
        //     ['student_code' => '000002', 'full_name' => 'Trần Thị Bích Ngọc'],
        //     ['student_code' => '000003', 'full_name' => 'Phạm Minh Đức'],
        //     ['student_code' => '000004', 'full_name' => 'Lê Hoàng Nam'],
        //     ['student_code' => '000005', 'full_name' => 'Đỗ Thị Lan'],
        //     ['student_code' => '000006', 'full_name' => 'Ngô Văn Huy'],
        //     ['student_code' => '000007', 'full_name' => 'Vũ Thị Mai'],
        //     ['student_code' => '000008', 'full_name' => 'Bùi Quốc Khánh'],
        //     ['student_code' => '000009', 'full_name' => 'Trịnh Thùy Dung'],
        //     ['student_code' => '000010', 'full_name' => 'Phan Anh Tuấn'],
        //     ['student_code' => '000011', 'full_name' => 'Nguyễn Thị Hạnh'],
        //     ['student_code' => '000012', 'full_name' => 'Lý Văn Long'],
        //     ['student_code' => '000013', 'full_name' => 'Hoàng Thu Trang'],
        //     ['student_code' => '000014', 'full_name' => 'Đặng Quang Huy'],
        //     ['student_code' => '000015', 'full_name' => 'Trần Mỹ Linh'],
        //     ['student_code' => '000016', 'full_name' => 'Nguyễn Thành Công'],
        //     ['student_code' => '000017', 'full_name' => 'Lưu Hải Đăng'],
        //     ['student_code' => '000018', 'full_name' => 'Phạm Thu Hương'],
        //     ['student_code' => '000019', 'full_name' => 'Đinh Văn Kiên'],
        //     ['student_code' => '000020', 'full_name' => 'Lê Thị Thảo'],
        //     ['student_code' => '000021', 'full_name' => 'Trương Hữu Phước'],
        //     ['student_code' => '000022', 'full_name' => 'Nguyễn Thị Yến'],
        //     ['student_code' => '000023', 'full_name' => 'Phan Quốc Bảo'],
        //     ['student_code' => '000024', 'full_name' => 'Đoàn Thị Như Quỳnh'],
        //     ['student_code' => '000025', 'full_name' => 'Nguyễn Duy Khánh'],
        //     ['student_code' => '000026', 'full_name' => 'Trần Ngọc Ánh'],
        //     ['student_code' => '000027', 'full_name' => 'Lưu Văn Toàn'],
        //     ['student_code' => '000028', 'full_name' => 'Phạm Bảo Trâm'],
        //     ['student_code' => '000029', 'full_name' => 'Võ Minh Tâm'],
        //     ['student_code' => '000030', 'full_name' => 'Ngô Thị Kim Chi'],

        //     ['student_code' => '000031', 'full_name' => 'Trần Quang Hưng'],
        //     ['student_code' => '000032', 'full_name' => 'Nguyễn Thị Thu Trang'],
        //     ['student_code' => '000033', 'full_name' => 'Lê Quốc Khánh'],
        //     ['student_code' => '000034', 'full_name' => 'Phạm Thị Hồng Nhung'],
        //     ['student_code' => '000035', 'full_name' => 'Đỗ Anh Dũng'],
        //     ['student_code' => '000036', 'full_name' => 'Vũ Thị Thanh Hoa'],
        //     ['student_code' => '000037', 'full_name' => 'Nguyễn Trọng Phú'],
        //     ['student_code' => '000038', 'full_name' => 'Bùi Thị Ngọc Lan'],
        //     ['student_code' => '000039', 'full_name' => 'Phan Hoàng Duy'],
        //     ['student_code' => '000040', 'full_name' => 'Trịnh Minh Thư'],
        //     ['student_code' => '000041', 'full_name' => 'Ngô Văn Cường'],
        //     ['student_code' => '000042', 'full_name' => 'Lý Thị Mai Hương'],
        //     ['student_code' => '000043', 'full_name' => 'Hoàng Văn Tài'],
        //     ['student_code' => '000044', 'full_name' => 'Đặng Thị Thu Hà'],
        //     ['student_code' => '000045', 'full_name' => 'Phạm Đức Mạnh'],
        //     ['student_code' => '000046', 'full_name' => 'Nguyễn Thị Quỳnh Anh'],
        //     ['student_code' => '000047', 'full_name' => 'Lê Hữu Nghĩa'],
        //     ['student_code' => '000048', 'full_name' => 'Trần Thị Thanh Tâm'],
        //     ['student_code' => '000049', 'full_name' => 'Vũ Minh Hiếu'],
        //     ['student_code' => '000050', 'full_name' => 'Nguyễn Bảo Trân'],
        //     ['student_code' => '000051', 'full_name' => 'Đỗ Văn Lâm'],
        //     ['student_code' => '000052', 'full_name' => 'Phan Thị Ngọc Diệp'],
        //     ['student_code' => '000053', 'full_name' => 'Lưu Đức Anh'],
        //     ['student_code' => '000054', 'full_name' => 'Ngô Thị Hương Giang'],
        //     ['student_code' => '000055', 'full_name' => 'Trần Quốc Hòa'],
        //     ['student_code' => '000056', 'full_name' => 'Phạm Thu Trang'],
        //     ['student_code' => '000057', 'full_name' => 'Đinh Tiến Dũng'],

        //     ['student_code' => '000058', 'full_name' => 'Nguyễn Thị Thanh'],
        //     ['student_code' => '000059', 'full_name' => 'Bùi Hồng Phúc'],
        //     ['student_code' => '000060', 'full_name' => 'Lý Thị Kim Oanh'],


        // ]);
    }
}
